version: '3.7'
volumes:
  wp-data:
networks:
  wp-network:
services:
  traefik:
    image: traefik:v2.4
#    environment:
#      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
#      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
#      - TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO=https
#      - TRAEFIK_ACCESSLOG=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./volumes/traefik-acme:/acme
      - ./log:/log
    networks:
      - wp-network
  db:
    image: mysql:5.7
    env_file:
      - .env.mysql
    volumes:
      - wp-data:/var/lib/mysql
    ports:
      - 8889:3306
    networks:
      - wp-network
  phpmyadmin:
    env_file:
      - .env.phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 3001:80
    networks:
      - wp-network
  wordpress:
    env_file:
      - .env.wordpress
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.wp-https.redirectscheme.scheme=https
      - traefik.http.routers.wp-http.entrypoints=web
      - traefik.http.routers.wp-http.rule=Host(`${WORDPRESS_DOMAIN}`)
      - traefik.http.routers.wp-http.middlewares=wp-https@docker
      - traefik.http.routers.wp.entrypoints=web-secure
      - traefik.http.routers.wp.rule=Host(`${WORDPRESS_DOMAIN}`)
      - traefik.http.routers.wp.tls=true
      - traefik.http.routers.wp.tls.certresolver=default
    depends_on:
      - db
    image: wordpress:latest
    ports:
#      - ${WORDPRESS_HOST_PORT}:80
      - 8888:80
    volumes:
      - ./wordpress-files:/var/www/html
    container_name: wordpress-site
    networks:
      - wp-network
